config/routes.rb
Rails.application.routes.draw do

  mount ActionCable.server => '/cable'

  resources :postits
	resources :settings, except: :show
  resources :components
  resources :sprints
  resources :teams
  resources :issues
  resources :advices
  resources :comments
  resources :kanban
  resources :cards do
    member do
      patch :move
    end
  end
  resources :workflows do
    member do
      patch :move
    end
  end
  resources :notifications do
    collection do
      post :mark_as_read
    end
  end
  resources :retrospectives do
    member do
      patch :move
    end
  end
  resources :postits do
    member do
      patch :move
      post :vote
      post :save
    end
  end

  devise_for :users, controllers: {registrations: 'registrations', omniauth_callbacks: 'users/omniauth_callbacks'}
  match 'users/:id', to: 'users#destroy', via: :delete, as: :admin_destroy_user
  get '/users/manage_users', to: 'users#manage_users', as: 'devise_manage_users'
	post '/users/manage_users', to: 'users#create'
	get '/users', to: 'users#index', as: 'users_index'
  post '/users/group', to: 'users#group_assigment', as: 'users_update_group'
	post '/users/config', to: 'users#setting_assigment', as: 'users_update_setting'

  get '/signin', to: 'jira_sessions#new'
  get '/callback', to: 'jira_sessions#authorize'
  get '/signout', to: 'jira_sessions#destroy'

  get '/oauth', to: 'trello_sessions#new'
  get '/oauth/authorize', to: 'trello_sessions#authorize', as:'oauth_authorize'

  get '/teams/:id/graph_points', to: 'teams#get_graph_data'
  get '/teams/:id/graph_stories', to: 'teams#get_graph_stories'
  get '/teams/:id/graph_bugs', to: 'teams#get_graph_bugs'
  get '/teams/:id/graph_leftovers', to: 'teams#stories_graph_data'
  get '/teams/:id/graph_no_estimates', to: 'teams#stories_points_graph_data'
  get '/teams/:id/graph_closed_by_day', to: 'teams#graph_closed_by_day'
  get '/teams/:id/graph_release_time', to: 'teams#graph_release_time'
  get '/teams/:id/graph_lead_time_bugs', to: 'teams#graph_lead_time_bugs'
  get '/teams/:id/graph_ratio_bugs_closed', to: 'teams#graph_ratio_bugs_closed'
  get '/teams/:id/graph_comulative_flow_diagram', to: 'teams#graph_comulative_flow_diagram'
  get '/teams/:id/graph_time_first_response', to: 'teams#graph_time_first_response'
  post '/teams/:id/cycle_time_chart', to: 'teams#cycle_time_chart'
  get '/teams/:id/key_results', to: 'teams#key_results', as: 'teams_key_results'
  get '/teams/:id/comulative_flow_diagram', to: 'teams#comulative_flow_diagram', as:'teams_comulative_flow_diagram'
  get '/teams/:id/support', to: 'teams#support', as: 'teams_support'
  get '/teams/boards_by_team/:proj_id', to: 'teams#boards_by_team', as: 'teams_boards_by_team'
  get '/teams/full_project_details/:proj_id', to: 'teams#full_project_details', as: 'teams_full_project_details'
  get '/teams/custom_fields_by_board/:board_id', to: 'teams#custom_fields_by_board', as: 'teams_custom_fields_by_board'

  get '/comments/by_board/:board_id', to:'comments#comments_by_board', as: 'comments_by_board'

  get '/montecarlo', to: 'montecarlo#show',as: 'montecarlo_show'
  post '/montecarlo/chart', to: 'montecarlo#montecarlo_chart', as: 'montecarlo_chart'


  get '/sprints/:id/graph_closed_by_day', to: 'sprints#graph_closed_by_day'
  get '/sprints/:id/graph_release_time', to: 'sprints#graph_release_time'
	get '/sprints/:proj_id/dashboard', to: 'sprints#dashboards', as: 'sprints_dashboards'

  # Will make board_id optional
  get '/import/sprint(/:board_id)', to: 'sprints#import', as: 'sprint_import'
  get '/import/issues', to: 'sprints#import_issues', as: 'sprint_import_issues'
  get '/refresh/:id/issues', to: 'sprints#refresh_issues', as: 'sprint_refresh_issues'

  get '/issues/sprint/:sprint_id', to: 'issues#sprint_issues', as: 'sprint_issues'
  get '/issues/key/:key', to:"issues#show", as: 'issues_key_show'
  post '/issues/search', to: 'issues#search', as: 'issues_search'

  get '/import/kanban(/:board_id)', to: 'kanban#import_issues', as: 'kanban_import_issues'

  get '/:id', to: 'home#dashboard', as: 'get_dashboard'
  #get '/:id/refresh', to: 'home#refresh', as: 'refresh_path'

	get '/landing/info', to: 'landing#info', as: 'landing_info'
  get '/landing/error/401', to: 'landing#error_401', as: 'landing_error_401'
  get '/landing/error/403', to: 'landing#error_403', as: 'landing_error_403'
	post '/register', to: 'landing#register', as: 'landing_register'

  post '/advices/mark_as_read', to: 'advices#mark_as_read', as: 'advices_mark_as_read'

  root to: 'home#dashboard'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

end

app/controllers/landing_controller.rb
class LandingController < ApplicationController
	layout 'landing'
	before_action :set_request, only: [:register]

	def info
		@user = User.new
	end


	def register
		logger.info "Sending a register email #{params[:user][:email]}"
		@user = User.new
		@user.email = params[:user][:email]
		UserNotifierMailer.send_info_email(@user).deliver
		respond_to do |format|
			format.html { redirect_to landing_info_path, notice: 'for showing interest on our product, will only contact you to notify new functionality or critical updates.' }
		end
	end

	private

	def set_request
		params.require(:user).permit(:email)
	end
end

app/views/landing/_base_landing.html.erb
<!DOCTYPE html>
<%= html_tag :lang => "en" do %>
  <head>
    <meta charset="utf-8">
    <title><%= [@title, app_name].compact.join(" - ") %></title>
    <%= csrf_meta_tags %>

    <!-- Ensure devices display responsive pages properly -->
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
    <script src="//html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
    <![endif]-->

    <!-- Le fonts -->
    <%= stylesheet_link_tag "//fonts.googleapis.com/css?family=Droid+Sans:400,700" %>
    <%= stylesheet_link_tag '//fonts.googleapis.com/css?family=Lato:300,400,700,900' %>

    <!-- Le styles -->
    <%= stylesheet_link_tag "application", :media => "all" %>
    <%= yield :styles %>

    <!-- Le javascript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <%= javascript_include_tag "//cdnjs.cloudflare.com/ajax/libs/modernizr/2.8.3/modernizr.min.js" %>

    <!-- This is for Google Maps integration, you can safely remove if not using Google Maps -->
    <%= javascript_include_tag "//maps.google.com/maps/api/js?sensor=true&.js" %>


    <%= javascript_include_tag "application" %>
    <%= yield :javascript %>

    <!-- Le fav and touch icons -->
    <%= favicon_link_tag %>
    <%# favicon_link_tag "apple-touch-icon.png", :rel => "apple-touch-icon" %>

    <%= yield :head %>
  </head>
  <body class="<%= yield (:body_class) %>">
  <%= render "layouts/navbar" %>

  <header>
    <%= yield :header %>
  </header>

  <%= yield :banner %>

  <div id="main" class="container-fluid">
    <div class="row">
      <%= yield %>
    </div> <!-- /.container -->
  </div> <!-- /#main -->

  </body>
<% end %>

app/views/landing/error_401.html.erb
<% content_for :body_class, "landing" %>

<style>
  html, body {
    height: 100%;
  }

  .well {
    padding: 4em;
  }

  .container{
    width:1025px;
  }

  .vertical-center {
    height:100%;
    width:100%;
    text-align: center;  /* align the inline(-block) elements horizontally */
    font: 0/0 a;         /* remove the gap between inline(-block) elements */
  }

  .vertical-center:before {    /* create a full-height inline block pseudo=element */
    content: ' ';
    display: inline-block;
    vertical-align: middle;  /* vertical alignment of the inline element */
    height: 100%;
  }

  .vertical-center > .container {
    max-width: 100%;
    display: inline-block;
    vertical-align: middle;  /* vertical alignment of the inline element */
    font: 16px/1 "Helvetica Neue", Helvetica, Arial, sans-serif;        /* <-- reset the font property */
  }

  @media (max-width: 768px) {
    .vertical-center:before {
      /* height: auto; */
      display: none;
    }
  }
</style>

<div class='vertical-center'>
  <div class="container text-center">

    <div class="row">
      <header class="text-center"></header>
    </div>
    <div class="row">
      <div class="col-xs-12 col-sm-12 col-md-12  col-lg-12 ">
        <div class="fa-icon text-blue-grey-400">
          <i class="fa fa-fw fa-2x fa-chain-broken"></i>
        </div>
        <div class='well'>
          <h2 class="mt0">Ups! Connection refused from external service</h2>
          <p>Vortrics wasn't able to reach the external service, either because a private secure connection is required or it requires extra login information.</p>
          <p><a href="/users/edit">Edit your credentials</a> and enter login data to access the external service.</p>
          <p>In case of a private secure connection required, we advice you to  <a href="https://github.com/eddygarcas/vortrics">clone Vortics</a> on your systems and run it from there.</p>
          <small class="text-muted">If you are the application owner check the logs for more information.</small>
        </div>
      </div>
    </div>
    <div class="row mt20">
      <div class="col-xs-12 col-sm-12 col-md-6 col-md-offset-3 col-lg-6 col-lg-offset3">
        <ul class="list-unstyled options">
          <li>If you want to cancel your account instead, <a href="/users/edit">edit your credentials</a> and press 'Cancel my account'</li>
        </ul>
      </div>
    </div>
  </div>
</div>

app/views/landing/error_403.html.erb
<% content_for :body_class, "landing" %>

<style>
  html, body {
    height: 100%;
  }

  .well {
    padding: 4em;
  }

  .container{
    width:1025px;
  }

  .vertical-center {
    height:100%;
    width:100%;
    text-align: center;  /* align the inline(-block) elements horizontally */
    font: 0/0 a;         /* remove the gap between inline(-block) elements */
  }

  .vertical-center:before {    /* create a full-height inline block pseudo=element */
    content: ' ';
    display: inline-block;
    vertical-align: middle;  /* vertical alignment of the inline element */
    height: 100%;
  }

  .vertical-center > .container {
    max-width: 100%;
    display: inline-block;
    vertical-align: middle;  /* vertical alignment of the inline element */
    font: 16px/1 "Helvetica Neue", Helvetica, Arial, sans-serif;        /* <-- reset the font property */
  }

  @media (max-width: 768px) {
    .vertical-center:before {
      /* height: auto; */
      display: none;
    }
  }
</style>

<div class='vertical-center'>
  <div class="container text-center">

    <div class="row">
      <header class="text-center"></header>
    </div>
    <div class="row">
      <div class="col-xs-12 col-sm-12 col-md-12  col-lg-12 ">
        <div class="fa-icon text-blue-grey-400">
          <i class="fa fa-fw fa-2x fa-info-circle"></i>
        </div>
        <div class='well'>
          <h2 class="mt0">Ups! have you requested access?</h2>
          <p>Request us access through our <a href="./landing/info"> landing page</a> or contact us for any further
            question.</p>
          <small class="text-muted">If you are the application owner check the logs for more information.</small>
        </div>
      </div>
    </div>
    <div class="row mt20">
      <div class="col-xs-12 col-sm-12 col-md-6 col-md-offset-3 col-lg-6 col-lg-offset3">
        <ul class="list-unstyled options">
          <li><a href="/users/edit">Edit your credentials</a></li>
        </ul>
      </div>
    </div>
  </div>
</div>

app/views/landing/info.html.erb
<% content_for :body_class, "landing" %>

<% content_for :header do %>
  <header class="video-header">
    <video playsinline autoplay muted loop>
      <source src="/images/vortrics_cover.mp4" type="video/mp4">
    </video>
  </header>
<% end %>

<main>

  <section class="getting-started">
    <div class="container">
      <div class="row">
        <div class="col-md-10 col-md-offset-1">
          <div class="text">
            <h1>Vortrics - Agile Metrics Board</h1>
            <p class="lead" style="color: lightgray;">Supports software product teams, Agile coaches and Scrum Masters,
              handling and visualise
              performance agile metrics
              in an Agile transformation.</p>
          </div>

        </div>

      </div>
      <div class="row">
        <div class="col-md-10 col-md-offset-1">
          <div class="col-md-4 text-xs-center text-md-left">
            <p style="color: lightgray">Clone Vortrics Github repository or try it out first.</p>
          </div>
          <div class="col-md-8">
            <%= link_to root_url, class: "social-icons btn btn-outline-inverse", style: "font-size: 24px;" do |url| %>
              <i class="fa fa-sign-in" style="font-size: 24px;"></i> Sign in with Github
            <% end %>
            <a href="https://github.com/eddygarcas/vortrics" class="social-icons btn  btn-outline-inverse" style="font-size: 24px;"><i class="fa fa-github" style="font-size: 24px;"></i>
              Clone in Github</a>
          </div>
        </div>
      </div>
    </div>
  </section>

  <section class="features">


    <div class="container">
      <p class="lead">
        <strong>Vortrics</strong> offers tools as well as support in an Agile transformation. Based on our on expertise
        we can
        help organizations to set up a 'Coach with data' system and boost product teams performance, coaching them on
        how
        to use these tools on their own benefit and for the sake of the organization they are working for.
        <br/>
        We are are currently working on offering free access but so far see what we would offer you.</p>


      <div class="row">
        <div class="col-xs-12 col-md-4">
          <section>
            <i class='fa fa-line-chart'></i>
            <h4>Overview</h4>
            <p>On this board you will Have a clear overview about team's performance trends, average story points and
              stories closed, variance, commitment vs. closed, story points vs. stories, cumulative flow diagram,...</p>
          </section>
        </div>
        <div class="col-xs-12 col-md-4">
          <section>
            <i class='fa fa-cogs'></i>
            <h4>On-Going Sprint </h4>
            <p>On this board you will be able to check out the sprint health on a daily basis, burn-down chart, blocked
              time, velocity variance,...</p>
          </section>
        </div>
        <div class="col-xs-12 col-md-4">
          <section>
            <i class='fa fa-signal fa-flip-horizontal'></i>
            <h4>Measure Cycle Time</h4>
            <p>Discover any workflow dysfunction by keeping an eye on the Cycle Time, discover blockers,
              roadblocks,...</p>
          </section>
        </div>
      </div>
      <div class="row">
        <div class="col-xs-12 col-md-4">
          <section>
            <i class='fa fa-sticky-note'></i>
            <h4>Remote Retrospectives</h4>
            <p>Thanks to action cable technology teams will now be able to run effective retrospectives remotely, customizing retro-boards, creating post-its, dot voting, comments and much more.</p>
          </section>
        </div>
        <div class="col-xs-12 col-md-4">
          <section>
            <i class='fa fa-map-o'></i>
            <h4>Forecasting</h4>
            <p>Set of forecasting tools that would help product owners to provide accurate estimations.</p>
          </section>
        </div>
        <div class="col-xs-12 col-md-4">
          <section>
            <i class='fa fa-certificate'></i>
            <h4>Agile Coach</h4>
            <p>Advise your teams based on your experience! by automatically analysing teams data to provide continuous
              improvement actions.</p>
          </section>
        </div>
      </div>
    </div>
  </section>


  <section class="getting-started">

    <div class="container">

      <div class="row">


        <div class="col-md-10 col-md-offset-1">
          <% flash.each do |type, message| %>
            <div class="alert alert-dismissable alert-bottom-border fade in" style="color:white;">
              <h4>Thank you!</h4>
              <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
              <%= fa_icon_tag "info-sign" %> <%= sanitize message %>
            </div>
          <% end %>

          <div class="col-md-7 text-center text-left">
            <p style="color: lightgray;font-size: 16px;"><i class="fa fa-envelope mr-2"></i><strong> Stay up to date
              with new Vortrics releases and future functionality.</strong></p>
          </div>
          <div class="col-md-5 text-xs-center text-right">

            <%= form_for @user, url: landing_register_path,
                         html: {class: "form-inline", novalidate: false} do |f| %>
              <%= f.error_notification %>
              <div class="text-center">

                <%= f.form_group :email do |f| %>
                  <%= f.email_field :email, autofocus: true, required: true, placeholder: 'email address', class: 'form-control col-xs-12 mr10 mb10', pattern: '[^@]+@[^@]+\.[a-zA-Z]{2,6}' %>
                  <%= f.submit value: 'Subscribe', class: 'btn btn-outline-default', style: 'padding:8px;' %>
                  <%= f.error_messages %>
                <% end %>
              </div>
            <% end %>
          </div>
        </div>
      </div>

    </div>
  </section>


  <section class='product-images'>
    <div class='container'>
      <div class='row'>
        <div class='col-sm-12' style="color: black;">
          <h2 class='h1 text-center'>Screenshots</h2>
          <p class="lead text-center">Look at <strong>Vortrics</strong> current features and boards. Feel free to
            contact
            us to know what
            we could do to support your Agile transformation.</p>

          <div class="panel-body" id="screenshots">
            <div id="carousel-example-generic" class="carousel slide">
              <!-- Indicators //-->
              <ol class="carousel-indicators">
                <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
                <li data-target="#carousel-example-generic" data-slide-to="1"></li>
                <li data-target="#carousel-example-generic" data-slide-to="2"></li>
                <li data-target="#carousel-example-generic" data-slide-to="3"></li>
                <li data-target="#carousel-example-generic" data-slide-to="4"></li>
              </ol>
              <!-- Wrapper for slides -->
              <div class="carousel-inner">
                <div class="item active">
                  <img alt="Overview" class="" src="/images/voardtrix_overview.png" width="100%">
                </div>
                <div class="item">
                  <img alt="Sprint board" class="" src="/images/voardtrix_sprint.png" width="100%">
                </div>
                <div class="item">
                  <img alt="Cycle Time analysis" class="" src="/images/voardtrix_cycletime.png" width="100%">
                </div>
                <div class="item">
                  <img alt="Maturity Framework" class="" src="/images/voardtrix_maturity.png" width="100%">
                </div>
                <div class="item">
                  <img alt="JIRA integration" class="" src="/images/voardtrix_jira.png" width="100%">
                </div>
              </div>
              <!-- Controls -->
              <a class="left carousel-control" href="#carousel-example-generic" data-slide="prev">
                <span class="icon-prev"></span>
              </a>
              <a class="right carousel-control" href="#carousel-example-generic" data-slide="next">
                <span class="icon-next"></span>
              </a>
            </div>
            <!-- carousel end //-->
          </div>


        </div>
      </div>
    </div>
  </section>
  <section class='cta'>
    <div class="container-fluid">
      <div class="row">
        <div class="col-sm-12 col-md-12">
          <h2 class="text-xs-center">“If you don't know where you are going any road can take you there”</h2>
        </div>
      </div>
      <div class="row">
        <div class="col-md-8 col-md-offset-2">
          <p class="lead text-xs-center">― Lewis Carroll, Alice in Wonderland</p>
        </div>
      </div>
    </div>
  </section>

  <%= render "layouts/footer_agent" %>

</main>