config/routes.rb
Rails.application.routes.draw do

  mount ActionCable.server => '/cable'

  resources :postits
	resources :settings, except: :show
  resources :components
  resources :sprints
  resources :teams
  resources :issues
  resources :advices
  resources :comments
  resources :kanban
  resources :cards do
    member do
      patch :move
    end
  end
  resources :workflows do
    member do
      patch :move
    end
  end
  resources :notifications do
    collection do
      post :mark_as_read
    end
  end
  resources :retrospectives do
    member do
      patch :move
    end
  end
  resources :postits do
    member do
      patch :move
      post :vote
      post :save
    end
  end

  devise_for :users, controllers: {registrations: 'registrations', omniauth_callbacks: 'users/omniauth_callbacks'}
  match 'users/:id', to: 'users#destroy', via: :delete, as: :admin_destroy_user
  get '/users/manage_users', to: 'users#manage_users', as: 'devise_manage_users'
	post '/users/manage_users', to: 'users#create'
	get '/users', to: 'users#index', as: 'users_index'
  post '/users/group', to: 'users#group_assigment', as: 'users_update_group'
	post '/users/config', to: 'users#setting_assigment', as: 'users_update_setting'

  get '/signin', to: 'jira_sessions#new'
  get '/callback', to: 'jira_sessions#authorize'
  get '/signout', to: 'jira_sessions#destroy'

  get '/oauth', to: 'trello_sessions#new'
  get '/oauth/authorize', to: 'trello_sessions#authorize', as:'oauth_authorize'

  get '/teams/:id/graph_points', to: 'teams#get_graph_data'
  get '/teams/:id/graph_stories', to: 'teams#get_graph_stories'
  get '/teams/:id/graph_bugs', to: 'teams#get_graph_bugs'
  get '/teams/:id/graph_leftovers', to: 'teams#stories_graph_data'
  get '/teams/:id/graph_no_estimates', to: 'teams#stories_points_graph_data'
  get '/teams/:id/graph_closed_by_day', to: 'teams#graph_closed_by_day'
  get '/teams/:id/graph_release_time', to: 'teams#graph_release_time'
  get '/teams/:id/graph_lead_time_bugs', to: 'teams#graph_lead_time_bugs'
  get '/teams/:id/graph_ratio_bugs_closed', to: 'teams#graph_ratio_bugs_closed'
  get '/teams/:id/graph_comulative_flow_diagram', to: 'teams#graph_comulative_flow_diagram'
  get '/teams/:id/graph_time_first_response', to: 'teams#graph_time_first_response'
  post '/teams/:id/cycle_time_chart', to: 'teams#cycle_time_chart'
  get '/teams/:id/key_results', to: 'teams#key_results', as: 'teams_key_results'
  get '/teams/:id/comulative_flow_diagram', to: 'teams#comulative_flow_diagram', as:'teams_comulative_flow_diagram'
  get '/teams/:id/support', to: 'teams#support', as: 'teams_support'
  get '/teams/boards_by_team/:proj_id', to: 'teams#boards_by_team', as: 'teams_boards_by_team'
  get '/teams/full_project_details/:proj_id', to: 'teams#full_project_details', as: 'teams_full_project_details'
  get '/teams/custom_fields_by_board/:board_id', to: 'teams#custom_fields_by_board', as: 'teams_custom_fields_by_board'

  get '/comments/by_board/:board_id', to:'comments#comments_by_board', as: 'comments_by_board'

  get '/montecarlo', to: 'montecarlo#show',as: 'montecarlo_show'
  post '/montecarlo/chart', to: 'montecarlo#montecarlo_chart', as: 'montecarlo_chart'


  get '/sprints/:id/graph_closed_by_day', to: 'sprints#graph_closed_by_day'
  get '/sprints/:id/graph_release_time', to: 'sprints#graph_release_time'
	get '/sprints/:proj_id/dashboard', to: 'sprints#dashboards', as: 'sprints_dashboards'

  # Will make board_id optional
  get '/import/sprint(/:board_id)', to: 'sprints#import', as: 'sprint_import'
  get '/import/issues', to: 'sprints#import_issues', as: 'sprint_import_issues'
  get '/refresh/:id/issues', to: 'sprints#refresh_issues', as: 'sprint_refresh_issues'

  get '/issues/sprint/:sprint_id', to: 'issues#sprint_issues', as: 'sprint_issues'
  get '/issues/key/:key', to:"issues#show", as: 'issues_key_show'
  post '/issues/search', to: 'issues#search', as: 'issues_search'

  get '/import/kanban(/:board_id)', to: 'kanban#import_issues', as: 'kanban_import_issues'

  get '/:id', to: 'home#dashboard', as: 'get_dashboard'
  #get '/:id/refresh', to: 'home#refresh', as: 'refresh_path'

	get '/landing/info', to: 'landing#info', as: 'landing_info'
  get '/landing/error/401', to: 'landing#error_401', as: 'landing_error_401'
  get '/landing/error/403', to: 'landing#error_403', as: 'landing_error_403'
	post '/register', to: 'landing#register', as: 'landing_register'

  post '/advices/mark_as_read', to: 'advices#mark_as_read', as: 'advices_mark_as_read'

  root to: 'home#dashboard'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

end

app/models/postit.rb
class Postit < ApplicationRecord
  acts_as_list scope: :retrospective

  belongs_to :retrospective
  belongs_to :user

  has_many :comments, -> {order(created_at: :desc)}, dependent: :destroy

  validates :text, presence: true

  def advice
    self
  end

end

app/controllers/postits_controller.rb
class PostitsController < ApplicationController
  before_action :set_postit, only: [:show, :edit, :update,:save, :destroy,:move,:vote]

  # GET /postits
  # GET /postits.json
  def index
    @postits = Postit.all
  end

  # GET /postits/1
  # GET /postits/1.json
  def show
  end

  # GET /postits/new
  def new
    @postit = Postit.new
  end

  # GET /postits/1/edit
  def edit
  end

  def move
    @postit.update(postit_params)
    broadcast_actioncable "retrospective","postitMoved", @postit.to_json(include: [:user,comments: {include: :actor }])
    render action: :show
  end

  def vote
    @postit.update(dots: @postit.dots.nil? ? 1 : @postit.dots+1)
    broadcast_actioncable "retrospective","postitVote", @postit.to_json
    render json: :success
  end

  def save
    @postit.update(description: postit_params[:description])
    broadcast_actioncable "retrospective", "savePostit", @postit.to_json
    render json: :success
  end

  # POST /postits
  # POST /postits.json
  def create
    @postit = Postit.new(postit_params)
    @postit.user = current_user

    respond_to do |format|
      if @postit.save
        broadcast_notification @postit
        broadcast_actioncable "retrospective", "createPostit", @postit.to_json(include: [:user,comments: {include: :actor }])
        format.html { redirect_to @postit, notice: 'Postit was successfully created.' }
        format.json { render json: @postit.to_json(include: :user) }
      else
        format.html { render :new }
        format.json { render json: @postit.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /postits/1
  # PATCH/PUT /postits/1.json
  def update
    respond_to do |format|
      if @postit.update(postit_params)
        format.html { redirect_to @postit, notice: 'Postit was successfully updated.' }
        format.json { render :show, status: :ok, location: @postit }
      else
        format.html { render :edit }
        format.json { render json: @postit.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /postits/1
  # DELETE /postits/1.json
  def destroy
    @postit.destroy
    respond_to do |format|
      ActionCable.server.broadcast "retrospective", { commit: 'deletePostit', payload: @postit.to_json }
      format.html { redirect_to postits_url, notice: 'Postit was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_postit
      @postit = Postit.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def postit_params
      params.require(:postit).permit(:text, :position, :dots, :description, :comments, :retrospective_id)
    end
end

app/views/postits/_form.html.erb
<%= form_for(@postit, html: { class: 'form-horizontal' }) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.form_group :text do |f| %>
      <%= f.label :text, class: 'control-label col-md-2' %>
      <div class='col-md-8'>
        <%= f.text_field :text, class: 'form-control' %>
        <%= f.error_messages %>
      </div>
    <% end %>

    <%= f.form_group :position do |f| %>
      <%= f.label :position, class: 'control-label col-md-2' %>
      <div class='col-md-8'>
        <%= f.number_field :position, class: 'form-control' %>
        <%= f.error_messages %>
      </div>
    <% end %>

    <%= f.form_group :dots do |f| %>
      <%= f.label :dots, class: 'control-label col-md-2' %>
      <div class='col-md-8'>
        <%= f.number_field :dots, class: 'form-control' %>
        <%= f.error_messages %>
      </div>
    <% end %>

    <%= f.form_group :comments do |f| %>
      <%= f.label :comments, class: 'control-label col-md-2' %>
      <div class='col-md-8'>
        <%= f.number_field :comments, class: 'form-control' %>
        <%= f.error_messages %>
      </div>
    <% end %>

    <%= f.form_group :retrospective do |f| %>
      <%= f.label :retrospective, class: 'control-label col-md-2' %>
      <div class='col-md-8'>
        <%= f.text_field :retrospective, class: 'form-control' %>
        <%= f.error_messages %>
      </div>
    <% end %>

  </div>

  <div class="form-actions">
    <div class="form-group">
      <div class="col-md-2"></div>
      <div class="col-md-8">
        <%= f.submit class: 'btn btn-primary' %>
        <%= link_to "Cancel", postits_path, class: 'btn' %>
      </div>
    </div>
  </div>
<% end %>

app/views/postits/edit.html.erb
<% @title = "Editing postit" %>

<% content_for :description do %>
<p>Edit this template in <code>app/views/postits/edit.html.erb</code>.</p>
<% end %>

<div class="container-fluid">
  <div class="row">
    <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
      <div class="sheet sheet-condensed">
        <div class="sheet-inner p30">
          <%= render 'form' %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/postits/index.html.erb
<% @title = "Listing postits" %>

<% content_for :description do %>
  <p>Edit this template in <code>app/views/postits/index.html.erb</code>.</p>
<% end %>

<% content_for :actions do %>
  <%= link_to new_postit_path, class: 'btn btn-primary btn-large pull-right' do %>
    <%= fa_icon_tag "plus" %> Add Postit
  <% end %>
<% end %>

<div class="container-fluid">
  <div class="row">
    <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
      <div class="sheet sheet-condensed">
        <div class="sheet-inner">
          <table class="table">
            <thead>
            <tr>
              <th>Text</th>
              <th>Position</th>
              <th>Dots</th>
              <th>Comments</th>
              <th>Retrospective</th>
              <th></th>
            </tr>
            </thead>
            <tbody>
            <% @postits.each do |postit| %>
              <tr>
                <td><%= postit.text %></td>
                <td><%= postit.position %></td>
                <td><%= postit.dots %></td>
                <td><%= postit.comments %></td>
                <td><%= postit.retrospective %></td>
                <td class="actions">
                  <%= link_to fa_icon_tag("eye"), postit, rel: 'tooltip', title: 'Show' %>
                  <%= link_to fa_icon_tag("pencil"), edit_postit_path(postit), rel: 'tooltip', title: 'Edit' %>
                  <%= link_to fa_icon_tag("trash-o"), postit, rel: 'tooltip', title: 'Delete',
                              data: {confirm: 'Are you sure?'}, method: :delete %>
                </td>
              </tr>
            <% end %>
            <% if @postits.length == 0 %>
              <tr>
                <td colspan=42 class='text-center'>No postits.</td>
              </tr>
            <% end %>
            </tbody>
          </table>
        </div><!-- /.sheet-inner -->
      </div><!-- /.sheet -->

      <%# Remove the trailing if condition if you're using pagination. %>
      <%= will_paginate @postits if @postits.respond_to?(:total_pages) %>
    </div>
  </div>
</div>

app/views/postits/new.html.erb
<% @title = "New postit" %>

<% content_for :description do %>
<p>Edit this template in <code>app/views/postits/new.html.erb</code>.</p>
<% end %>

<div class="container-fluid">
  <div class="row">
    <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
      <%= render 'form' %>
    </div>
  </div>
</div>

app/views/postits/show.html.erb
<% @title = "Showing postit" %>

<% content_for :description do %>
  <p>Edit this template in <code>app/views/postits/show.html.erb</code>.</p>
  <% end %>

  <div class="container-fluid">
    <div class="row">
      <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
        <div class="sheet sheet-condensed">
          <div class="sheet-inner p30">
            <div class="form-horizontal">
                              <div class="form-inputs">
                 <div class="form-group">
                    <label class="col-md-2 control-label">Text</label>
                    <div class="col-md-8">
                     <div class="form-control uneditable-input">
                        <span>
                          <%= @postit.text %>
                        </span>
                    </div>
                  </div>
                </div>
              </div>


                              <div class="form-inputs">
                 <div class="form-group">
                    <label class="col-md-2 control-label">Position</label>
                    <div class="col-md-8">
                     <div class="form-control uneditable-input">
                        <span>
                          <%= @postit.position %>
                        </span>
                    </div>
                  </div>
                </div>
              </div>


                              <div class="form-inputs">
                 <div class="form-group">
                    <label class="col-md-2 control-label">Dots</label>
                    <div class="col-md-8">
                     <div class="form-control uneditable-input">
                        <span>
                          <%= @postit.dots %>
                        </span>
                    </div>
                  </div>
                </div>
              </div>


                              <div class="form-inputs">
                 <div class="form-group">
                    <label class="col-md-2 control-label">Comments</label>
                    <div class="col-md-8">
                     <div class="form-control uneditable-input">
                        <span>
                          <%= @postit.comments %>
                        </span>
                    </div>
                  </div>
                </div>
              </div>


                              <div class="form-inputs">
                 <div class="form-group">
                    <label class="col-md-2 control-label">Retrospective</label>
                    <div class="col-md-8">
                     <div class="form-control uneditable-input">
                        <span>
                          <%= @postit.retrospective %>
                        </span>
                    </div>
                  </div>
                </div>
              </div>


                            <div class="form-actions col-md-offset-2">
                <%= link_to fa_icon_tag("pencil") + ' Edit', edit_postit_path(@postit), class: 'btn btn-primary' %>
                <%= link_to 'Back', postits_path, class: 'btn' %>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>