config/routes.rb
Rails.application.routes.draw do

  mount ActionCable.server => '/cable'

  resources :postits
	resources :settings, except: :show
  resources :components
  resources :sprints
  resources :teams
  resources :issues
  resources :advices
  resources :comments
  resources :kanban
  resources :cards do
    member do
      patch :move
    end
  end
  resources :workflows do
    member do
      patch :move
    end
  end
  resources :notifications do
    collection do
      post :mark_as_read
    end
  end
  resources :retrospectives do
    member do
      patch :move
    end
  end
  resources :postits do
    member do
      patch :move
      post :vote
      post :save
    end
  end

  devise_for :users, controllers: {registrations: 'registrations', omniauth_callbacks: 'users/omniauth_callbacks'}
  match 'users/:id', to: 'users#destroy', via: :delete, as: :admin_destroy_user
  get '/users/manage_users', to: 'users#manage_users', as: 'devise_manage_users'
	post '/users/manage_users', to: 'users#create'
	get '/users', to: 'users#index', as: 'users_index'
  post '/users/group', to: 'users#group_assigment', as: 'users_update_group'
	post '/users/config', to: 'users#setting_assigment', as: 'users_update_setting'

  get '/signin', to: 'jira_sessions#new'
  get '/callback', to: 'jira_sessions#authorize'
  get '/signout', to: 'jira_sessions#destroy'

  get '/oauth', to: 'trello_sessions#new'
  get '/oauth/authorize', to: 'trello_sessions#authorize', as:'oauth_authorize'

  get '/teams/:id/graph_points', to: 'teams#get_graph_data'
  get '/teams/:id/graph_stories', to: 'teams#get_graph_stories'
  get '/teams/:id/graph_bugs', to: 'teams#get_graph_bugs'
  get '/teams/:id/graph_leftovers', to: 'teams#stories_graph_data'
  get '/teams/:id/graph_no_estimates', to: 'teams#stories_points_graph_data'
  get '/teams/:id/graph_closed_by_day', to: 'teams#graph_closed_by_day'
  get '/teams/:id/graph_release_time', to: 'teams#graph_release_time'
  get '/teams/:id/graph_lead_time_bugs', to: 'teams#graph_lead_time_bugs'
  get '/teams/:id/graph_ratio_bugs_closed', to: 'teams#graph_ratio_bugs_closed'
  get '/teams/:id/graph_comulative_flow_diagram', to: 'teams#graph_comulative_flow_diagram'
  get '/teams/:id/graph_time_first_response', to: 'teams#graph_time_first_response'
  post '/teams/:id/cycle_time_chart', to: 'teams#cycle_time_chart'
  get '/teams/:id/key_results', to: 'teams#key_results', as: 'teams_key_results'
  get '/teams/:id/comulative_flow_diagram', to: 'teams#comulative_flow_diagram', as:'teams_comulative_flow_diagram'
  get '/teams/:id/support', to: 'teams#support', as: 'teams_support'
  get '/teams/boards_by_team/:proj_id', to: 'teams#boards_by_team', as: 'teams_boards_by_team'
  get '/teams/full_project_details/:proj_id', to: 'teams#full_project_details', as: 'teams_full_project_details'
  get '/teams/custom_fields_by_board/:board_id', to: 'teams#custom_fields_by_board', as: 'teams_custom_fields_by_board'

  get '/comments/by_board/:board_id', to:'comments#comments_by_board', as: 'comments_by_board'

  get '/montecarlo', to: 'montecarlo#show',as: 'montecarlo_show'
  post '/montecarlo/chart', to: 'montecarlo#montecarlo_chart', as: 'montecarlo_chart'


  get '/sprints/:id/graph_closed_by_day', to: 'sprints#graph_closed_by_day'
  get '/sprints/:id/graph_release_time', to: 'sprints#graph_release_time'
	get '/sprints/:proj_id/dashboard', to: 'sprints#dashboards', as: 'sprints_dashboards'

  # Will make board_id optional
  get '/import/sprint(/:board_id)', to: 'sprints#import', as: 'sprint_import'
  get '/import/issues', to: 'sprints#import_issues', as: 'sprint_import_issues'
  get '/refresh/:id/issues', to: 'sprints#refresh_issues', as: 'sprint_refresh_issues'

  get '/issues/sprint/:sprint_id', to: 'issues#sprint_issues', as: 'sprint_issues'
  get '/issues/key/:key', to:"issues#show", as: 'issues_key_show'
  post '/issues/search', to: 'issues#search', as: 'issues_search'

  get '/import/kanban(/:board_id)', to: 'kanban#import_issues', as: 'kanban_import_issues'

  get '/:id', to: 'home#dashboard', as: 'get_dashboard'
  #get '/:id/refresh', to: 'home#refresh', as: 'refresh_path'

	get '/landing/info', to: 'landing#info', as: 'landing_info'
  get '/landing/error/401', to: 'landing#error_401', as: 'landing_error_401'
  get '/landing/error/403', to: 'landing#error_403', as: 'landing_error_403'
	post '/register', to: 'landing#register', as: 'landing_register'

  post '/advices/mark_as_read', to: 'advices#mark_as_read', as: 'advices_mark_as_read'

  root to: 'home#dashboard'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

end

app/models/setting.rb
class Setting < ApplicationRecord
  #after_initialize :init
  has_many :configs, dependent: :destroy
  has_many :users, through: :configs
  has_many :workflow, dependent: :destroy
  has_many :teams, dependent: :destroy

  URL_REGEXP = /\A(http|https):\/\/[a-z0-9]+([\-\.]{1}[a-z0-9]+)*\.[a-z]{2,5}(:[0-9]{1,5})?(\/.*)?\z/
  SM_REGEX = /[a-zA-Z](-)SHA[0-9]/
  PATH_REGEXP = /\A(\/)[a-z0-9]/

  validates :name, presence: {message: "Better define a name for this connection."}
  validates :key_file, presence: {message: "OAuth requires a certification file."}, if: :oauth?
  validates :signature_method, presence: {message: "Signature method is required for OAuth."}, if: :oauth?
  validates :signature_method, format: {with: SM_REGEX, message: "You provided an invalid signature method."}, if: :oauth?
  validates :site, presence: {message: "Site cannot be blank"}, unless: :tokenized?
  validates :base_path, presence: {message: "Base path cannot be blank"}, unless: :tokenized?
  validates :site, format: {with: URL_REGEXP, message: "You provided invalid URL"}, unless: :tokenized?
  validates :base_path, format: {with: PATH_REGEXP, message: "You provided invalid base path"}, unless: :tokenized?
  validates :login, presence: {message: "Login cannot be blank using a Basic authorisation."}, unless: -> record {record.oauth? || record.tokenized?}
  validates :password, presence: {message: "Password cannot be blank using a Basic Authorization."}, unless: -> record {record.oauth? || record.tokenized?}

  def service
    Service.find_by_setting_id(id)
  end

  def provider
    service&.provider.presence || :jira.to_s
  end

  def tokenized?
    !provider.eql? :jira.to_s
  end

  def locked?
    oauth? || tokenized?
  end

  def workflow_tags_for column_name
    begin
      Rails.cache.fetch("column_status_#{id}_#{column_name}", expires_in: 1.minutes) {
        workflow.where(name: column_name).first.cards.pluck(:name)
      }
    rescue NoMethodError
      nil
    end
  end

  def teams?
    Team.by_setting(id).present?
  end

end

app/controllers/settings_controller.rb
class SettingsController < ApplicationController
	layout 'sidenav'
	before_action :set_setting, only: [:edit, :update, :destroy]
	before_action :team_session
	before_action :registered_user?, only: [:index,:edit,:destroy,:update]
	# GET /settings
	# GET /settings.json
	def index
		@settings = current_user.admin? ? Setting.all : [current_user.setting]
		redirect_to new_setting_url unless @settings.any?
	end

	# GET /settings/1
	# GET /settings/1.json
	def show
	end

	# GET /settings/new
	def new
		@setting = Setting.new
		flash.discard
		flash[:default] = Vortrics.config[:messages][:first_steps]
	end

	# GET /settings/1/edit
	def edit
	end

	# POST /settings
	# POST /settings.json
	def create
		@setting = Setting.new(setting_params)
		unless setting_params[:key_data].blank?
			@setting.key_file = setting_params[:key_data].original_filename
			@setting.key_data = setting_params[:key_data].tempfile.read
		end
		respond_to do |format|
			if @setting.save
				current_user.save_dependent(@setting.id) if current_user.guest?
				Workflow.create_by_setting(@setting.id)
				format.html { redirect_to root_url }
				format.json { render :show, status: :created, location: @setting }
			else
				format.html { render :new }
				format.json { render json: @setting.errors, status: :unprocessable_entity }
			end
		end
	end

	# PATCH/PUT /settings/1
	# PATCH/PUT /settings/1.json
	def update
		respond_to do |format|
			unless setting_params[:key_data].blank?
				@setting.key_file = setting_params[:key_data].original_filename
			end
			if @setting.update(setting_params)
				unless setting_params[:key_data].blank?
					@setting.key_data = setting_params[:key_data].tempfile.read
					@setting.save
				end
				format.html { redirect_to settings_url, notice: 'Setting was successfully updated.' }
				format.json { render :show, status: :ok, location: @setting }
			else
				format.html { render :edit }
				format.json { render json: @setting.errors, status: :unprocessable_entity }
			end
		end
	end

	# DELETE /settings/1
	# DELETE /settings/1.json
	def destroy
		@setting.destroy
		respond_to do |format|
			format.html { redirect_to settings_url, notice: 'Setting was successfully destroyed.' }
			format.json { head :no_content }
		end
	end

	private

	# Use callbacks to share common setup or constraints between actions.
	def set_setting
		@setting = Setting.find(params[:id])
	end

	# Never trust parameters from the scary internet, only allow the white list through.
	def setting_params
		params.require(:setting).permit(:name, :site, :base_path, :debug, :signature_method, :key_file, :key_data, :consumer_key, :oauth, :usessl , :login, :password)
	end
end

app/helpers/settings_helper.rb
module SettingsHelper
	include Connect
end

app/views/settings/_form.html.erb
<%= form_for(@setting, html: { multipart: true, class: 'form-horizontal form-control-lg' }) do |f| %>
  <%= f.error_notification %>
  <div class="form-inputs">
    <%= f.form_group :site do |f| %>
      <%= f.label :name, class: 'control-label col-md-2' %>
      <div class='col-md-4'>
        <div class="input-group leading">
          <%= f.text_field :name, class: 'form-control form-control-lg', placeholder: "Connection name", disabled: f.object.persisted? %>
        </div>
        <%= f.error_messages %>
      </div>
    <% end %>


    <%= f.form_group :site do |f| %>
      <%= f.label :site, class: 'control-label col-md-2' %>
      <div class='col-md-4'>
        <div class="input-group leading">
          <span class="input-group-addon">https</span>
          <%= f.text_field :site, class: 'form-control form-control-lg', placeholder: "https://jira.yourrestserver.com" %>
        </div>
        <%= f.error_messages %>
      </div>
    <% end %>

    <%= f.form_group :base_path do |f| %>
      <%= f.label :base_path, class: 'control-label col-md-2' %>
      <div class='col-md-4'>
        <%= f.text_field :base_path, class: 'form-control form-control-lg', placeholder: "/rest/api/2" %>
        <%= f.error_messages %>
      </div>
    <% end %>

    <%= f.form_group :usessl do |f| %>
      <%= f.label "SSL", class: 'control-label col-md-2' %>
      <div class='col-md-6'>
        <label class="switch switch-success small">
          <%= f.check_box :usessl, class: 'form-control form-control-lg',id: :usesslcheck, checked: @setting.usessl, data: { behaviour: 'usesslcheck'}  %>
          <span></span>
        </label>
        <%= f.error_messages %>
        <p class="small">Consider not using SSL if running locally or JIRA server not in a secure sockets</p>
      </div>
    <% end %>

    <%= f.form_group :oauth do |f| %>
      <%= f.label :oauth, class: 'control-label col-md-2' %>
      <div class='col-md-6'>
        <label class="switch switch-success small">
          <%= f.check_box :oauth, class: 'form-control form-control-lg',id: :oauthswitch, checked: @setting.oauth, data: { behaviour: 'oauthswitch'} %>
          <span></span>
        </label>
        <%= f.error_messages %>
        <p class="small">We strongly recommend setting up a OAuth authentication, will approve interacting with JIRA
          without giving away your password. This option requires a previous configuration of Vortrics as a consumer in JIRA, using application links. </p>
      </div>
    <% end %>

    <div style="display:none;"  class="animate-fade-in-500" id="basic">
      <%= f.form_group :login do |f| %>
        <%= f.label :login, class: 'control-label col-md-2' %>
        <div class='col-md-2'>
          <%= f.text_field :login, class: 'form-control form-control-lg' %>
          <%= f.error_messages %>
        </div>
      <% end %>

      <%= f.form_group :password do |f| %>
        <%= f.label :password, class: 'control-label col-md-2' %>
        <div class='col-md-2'>
          <%= f.password_field :password, class: 'form-control form-control-lg' %>
          <%= f.error_messages %>
        </div>
      <% end %>
    </div>

    <div style="display:block;" id="oauth" class="animate-fade-in-500">

    <%= f.form_group :signature_method do |f| %>
      <%= f.label :signature_method, class: 'control-label col-md-2' %>
      <div class='col-md-2'>
        <%= f.text_field :signature_method, class: 'form-control form-control-lg', placeholder: "RSA-SHA1" %>
        <%= f.error_messages %>
      </div>
    <% end %>

    <%= f.form_group :key_file do |f| %>
      <%= f.label :key_file, class: 'control-label col-md-2' %>
      <div class='col-md-4'>
        <div class="input-group leading">
          <%= f.file_field :key_data, class: 'form-control form-control-lg', accept: 'text/pem' %>
          <span class="input-group-addon">.pem</span>
        </div>
        <p class="small">OAuth authentication requires generate an RSA public/private key pair. Upload here the private
          key and the
          public in JIRA.</p>
        <%= f.error_messages %>
      </div>
    <% end %>

    <%= f.form_group :key_data do |f| %>
      <%= f.label ' ', class: 'control-label col-md-2' %>
      <div class='col-md-8'>
        <div class="input-group leading">
          <%= content_tag :p, @setting.key_data.slice(0,50), class: 'small' %>
        </div>
      </div>
    <% end if @setting.key_data.present? %>


    <%= f.form_group :consumer_key do |f| %>
      <%= f.label :consumer_key, class: 'control-label col-md-2' %>
      <div class='col-md-6'>
        <%= f.text_field :consumer_key, class: 'form-control form-control-lg' %>
        <p class="small">Unique Hash value required to setup OAuth authentication in JIRA. Has to be the same in both
          sides.</p>
        <%= f.error_messages %>
      </div>
    <% end %>

    </div>


    <%= f.form_group :debug do |f| %>
      <%= f.label :debug, class: 'control-label col-md-2' %>
      <div class='col-md-2'>
        <label class="switch switch-success small">
          <%= f.check_box :debug, class: 'form-control form-control-lg' %>
          <span></span>
        </label>
        <%= f.error_messages %>
      </div>
    <% end %>

  </div>

  <div class="form-actions">
    <div class="form-group">
      <div class="col-md-2"></div>
      <div class="col-md-8">
        <%= f.submit class: 'btn btn-primary' %>
        <%= link_to "Cancel", settings_path, class: 'btn' %>
      </div>
    </div>
  </div>
<% end %>

app/views/settings/edit.html.erb
<% @title = "Settings" %>

<% content_for :description do %>
  <p><%= vt_project_icon %>
    Settings</p>

<% end %>

<br/>
<div class="container-fluid col-xs-12 col-sm-12 col-md-12 col-lg-12">
  <div class="row sheet sheet-condensed">
    <div class="panel panel-default sheet-inner">
      <div class="panel-heading">
        <span class="fa fa-cog"></span>
        Edit <%= @setting.name %> server API provider
      </div>
      <p class="panel-body">
        <%= render 'form' %>
      </p>
    </div>
  </div>
</div>

app/views/settings/index.html.erb
<% @title = "External services" %>

<% content_for :description do %>
  <p><%= vt_project_icon %>
    External service</p>
  <%= render 'layouts/settings_nav' %>
<% end %>


<% content_for :actions do %>
  <%=
    link_to_if current_user&.setting.present?, "", {} do |name|
      link_to fa_icon_tag("plus") << "Add Setting", new_setting_path, class: "btn btn-primary btn-large pull-right"
    end
  %>
<% end %>
<%= render "layouts/flashes" %>
<div class="container-fluid mt15">

  <div class="row">
    <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
      <div class="sheet sheet-condensed">
        <div class="sheet-inner">
          <table class="table">
            <thead>
            <tr>
              <th>Name</th>
              <th>Site</th>
              <th>Base path</th>
              <th>Signature method</th>
              <th>Key file</th>
              <th>Consumer key</th>
              <th>OAuth</th>
              <th></th>
            </tr>
            </thead>
            <tbody>
            <% @settings.each do |setting| %>
              <tr>
                <td><%= setting.name %></td>
                <td><%= setting.site %></td>
                <td><%= setting.base_path %></td>
                <td><%= setting.signature_method %></td>
                <td><%= setting.key_file %></td>
                <td><%= setting.consumer_key %></td>
                <td><%= fa_icon_tag("lock") if setting.locked? %></td>
                <td class="actions">
                  <%= link_to fa_icon_tag("pencil"), edit_setting_path(setting), rel: 'tooltip', title: 'Edit' if current_user.registered? %>
                  <%= link_to fa_icon_tag("trash-o"), setting, rel: 'tooltip', title: 'Delete', data: { confirm: 'Are you sure?' }, method: :delete %>
                </td>
              </tr>
            <% end %>
            <% if @settings.length == 0 %>
              <tr>
                <td colspan=42 class='text-center'>No settings.</td>
              </tr>
            <% end %>
            </tbody>
          </table>
        </div><!-- /.sheet-inner -->
      </div><!-- /.sheet -->

      <%# Remove the trailing if condition if you're using pagination. %>
      <%= will_paginate @settings if @settings.respond_to?(:total_pages) %>
    </div>
  </div>
</div>

app/views/settings/new.html.erb
<% @title = "Settings" %>

<% content_for :description do %>
  <p><%= vt_project_icon %>
    Settings</p>

<% end %>

<br/>
<div class="container-fluid col-xs-12 col-sm-12 col-md-12 col-lg-12">
  <%= render "layouts/flashes" %>

  <div class="row sheet sheet-condensed">
    <div class="panel panel-default sheet-inner">
      <div class="panel-heading">
        <span class="fa fa-cog"></span>
        Add new REST server API provider
      </div>
      <p class="panel-body">
        <%= render 'form' %>
      </p>
    </div>
  </div>
</div>