config/routes.rb
Rails.application.routes.draw do

  mount ActionCable.server => '/cable'

  resources :postits
	resources :settings, except: :show
  resources :components
  resources :sprints
  resources :teams
  resources :issues
  resources :advices
  resources :comments
  resources :kanban
  resources :cards do
    member do
      patch :move
    end
  end
  resources :workflows do
    member do
      patch :move
    end
  end
  resources :notifications do
    collection do
      post :mark_as_read
    end
  end
  resources :retrospectives do
    member do
      patch :move
    end
  end
  resources :postits do
    member do
      patch :move
      post :vote
      post :save
    end
  end

  devise_for :users, controllers: {registrations: 'registrations', omniauth_callbacks: 'users/omniauth_callbacks'}
  match 'users/:id', to: 'users#destroy', via: :delete, as: :admin_destroy_user
  get '/users/manage_users', to: 'users#manage_users', as: 'devise_manage_users'
	post '/users/manage_users', to: 'users#create'
	get '/users', to: 'users#index', as: 'users_index'
  post '/users/group', to: 'users#group_assigment', as: 'users_update_group'
	post '/users/config', to: 'users#setting_assigment', as: 'users_update_setting'

  get '/signin', to: 'jira_sessions#new'
  get '/callback', to: 'jira_sessions#authorize'
  get '/signout', to: 'jira_sessions#destroy'

  get '/oauth', to: 'trello_sessions#new'
  get '/oauth/authorize', to: 'trello_sessions#authorize', as:'oauth_authorize'

  get '/teams/:id/graph_points', to: 'teams#get_graph_data'
  get '/teams/:id/graph_stories', to: 'teams#get_graph_stories'
  get '/teams/:id/graph_bugs', to: 'teams#get_graph_bugs'
  get '/teams/:id/graph_leftovers', to: 'teams#stories_graph_data'
  get '/teams/:id/graph_no_estimates', to: 'teams#stories_points_graph_data'
  get '/teams/:id/graph_closed_by_day', to: 'teams#graph_closed_by_day'
  get '/teams/:id/graph_release_time', to: 'teams#graph_release_time'
  get '/teams/:id/graph_lead_time_bugs', to: 'teams#graph_lead_time_bugs'
  get '/teams/:id/graph_ratio_bugs_closed', to: 'teams#graph_ratio_bugs_closed'
  get '/teams/:id/graph_comulative_flow_diagram', to: 'teams#graph_comulative_flow_diagram'
  get '/teams/:id/graph_time_first_response', to: 'teams#graph_time_first_response'
  post '/teams/:id/cycle_time_chart', to: 'teams#cycle_time_chart'
  get '/teams/:id/key_results', to: 'teams#key_results', as: 'teams_key_results'
  get '/teams/:id/comulative_flow_diagram', to: 'teams#comulative_flow_diagram', as:'teams_comulative_flow_diagram'
  get '/teams/:id/support', to: 'teams#support', as: 'teams_support'
  get '/teams/boards_by_team/:proj_id', to: 'teams#boards_by_team', as: 'teams_boards_by_team'
  get '/teams/full_project_details/:proj_id', to: 'teams#full_project_details', as: 'teams_full_project_details'
  get '/teams/custom_fields_by_board/:board_id', to: 'teams#custom_fields_by_board', as: 'teams_custom_fields_by_board'

  get '/comments/by_board/:board_id', to:'comments#comments_by_board', as: 'comments_by_board'

  get '/montecarlo', to: 'montecarlo#show',as: 'montecarlo_show'
  post '/montecarlo/chart', to: 'montecarlo#montecarlo_chart', as: 'montecarlo_chart'


  get '/sprints/:id/graph_closed_by_day', to: 'sprints#graph_closed_by_day'
  get '/sprints/:id/graph_release_time', to: 'sprints#graph_release_time'
	get '/sprints/:proj_id/dashboard', to: 'sprints#dashboards', as: 'sprints_dashboards'

  # Will make board_id optional
  get '/import/sprint(/:board_id)', to: 'sprints#import', as: 'sprint_import'
  get '/import/issues', to: 'sprints#import_issues', as: 'sprint_import_issues'
  get '/refresh/:id/issues', to: 'sprints#refresh_issues', as: 'sprint_refresh_issues'

  get '/issues/sprint/:sprint_id', to: 'issues#sprint_issues', as: 'sprint_issues'
  get '/issues/key/:key', to:"issues#show", as: 'issues_key_show'
  post '/issues/search', to: 'issues#search', as: 'issues_search'

  get '/import/kanban(/:board_id)', to: 'kanban#import_issues', as: 'kanban_import_issues'

  get '/:id', to: 'home#dashboard', as: 'get_dashboard'
  #get '/:id/refresh', to: 'home#refresh', as: 'refresh_path'

	get '/landing/info', to: 'landing#info', as: 'landing_info'
  get '/landing/error/401', to: 'landing#error_401', as: 'landing_error_401'
  get '/landing/error/403', to: 'landing#error_403', as: 'landing_error_403'
	post '/register', to: 'landing#register', as: 'landing_register'

  post '/advices/mark_as_read', to: 'advices#mark_as_read', as: 'advices_mark_as_read'

  root to: 'home#dashboard'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

end

app/models/card.rb
class Card < ApplicationRecord
  acts_as_list scope: :workflow
  belongs_to :workflow

  scope :by_list_name, -> (name) {joins(:workflow).where({workflows: {name: name}})}

  validates :name, presence: true
  before_save :name_downcase

  def name_downcase
    self.name.downcase!
  end
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
  before_action :set_card, only: [:show, :edit, :update, :destroy, :move]

  # GET /cards
  # GET /cards.json
  def index
    @cards = Card.all
  end

  # GET /cards/1
  # GET /cards/1.json
  def show
  end

  # GET /cards/new
  def new
    @card = Card.new
  end

  # GET /cards/1/edit
  def edit
  end

  def move
    @card.update(card_params)
    render action: :show
  end

  # POST /cards
  # POST /cards.json
  def create
    @card = Card.new(card_params)

    respond_to do |format|
      if @card.save
        format.html { redirect_to workflows_path, notice: 'Card was successfully created.' }
        format.json { render :show, status: :created, location: @card }
      else
        format.html { render :new }
        format.json { render json: @card.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cards/1
  # PATCH/PUT /cards/1.json
  def update
    respond_to do |format|
      if @card.update(card_params)
        format.html { redirect_to @card, notice: 'Card was successfully updated.' }
        format.json { render :show, status: :ok, location: @card }
      else
        format.html { render :edit }
        format.json { render json: @card.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cards/1
  # DELETE /cards/1.json
  def destroy
    @card.destroy
    respond_to do |format|
      format.html { redirect_to cards_url, notice: 'Card was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_card
      @card = Card.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def card_params
      params.require(:card).permit(:workflow_id,:name,:position)
    end
end

app/views/cards/_form.html.erb
<%= form_for(@card, html: { class: 'form-horizontal' }) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
  </div>

  <div class="form-actions">
    <div class="form-group">
      <div class="col-md-2"></div>
      <div class="col-md-8">
        <%= f.submit class: 'btn btn-primary' %>
        <%= link_to "Cancel", cards_path, class: 'btn' %>
      </div>
    </div>
  </div>
<% end %>

app/views/cards/edit.html.erb
<% @title = "Editing card" %>

<% content_for :description do %>
<p>Edit this template in <code>app/views/cards/edit.html.erb</code>.</p>
<% end %>

<div class="container-fluid">
  <div class="row">
    <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
      <div class="sheet sheet-condensed">
        <div class="sheet-inner p30">
          <%= render 'form' %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/cards/index.html.erb
<% @title = "Listing cards" %>

<% content_for :description do %>
<p>Edit this template in <code>app/views/cards/index.html.erb</code>.</p>
<% end %>

<% content_for :actions do %>
<%= link_to new_card_path, class: 'btn btn-primary btn-large pull-right' do %>
<%= fa_icon_tag "plus" %> Add Card
<% end %>
<% end %>

<div class="container-fluid">
  <div class="row">
    <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
      <div class="sheet sheet-condensed">
        <div class="sheet-inner">
          <table class="table">
            <thead>
              <tr>
                                <th></th>
              </tr>
            </thead>
            <tbody>
              <% @cards.each do |card| %>
              <tr>
                                <td class="actions">
                  <%= link_to fa_icon_tag("eye"), card, rel: 'tooltip', title: 'Show' %>
                  <%= link_to fa_icon_tag("pencil"), edit_card_path(card), rel: 'tooltip', title: 'Edit' %>
                  <%= link_to fa_icon_tag("trash-o"), card, rel: 'tooltip', title: 'Delete',
                  data: { confirm: 'Are you sure?' }, method: :delete %>
                </td>
              </tr>
              <% end %>
              <% if @cards.length == 0 %>
              <tr><td colspan=42 class='text-center'>No cards.</td></tr>
              <% end %>
            </tbody>
          </table>
        </div><!-- /.sheet-inner -->
      </div><!-- /.sheet -->

            <%# Remove the trailing if condition if you're using pagination. %>
      <%= will_paginate @cards if @cards.respond_to?(:total_pages) %>
                </div>
  </div>
</div>

app/views/cards/new.html.erb
<% @title = "New card" %>

<% content_for :description do %>
<p>Edit this template in <code>app/views/cards/new.html.erb</code>.</p>
<% end %>

<div class="container-fluid">
  <div class="row">
    <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
      <%= render 'form' %>
    </div>
  </div>
</div>

app/views/cards/show.html.erb
<% @title = "Showing card" %>

<% content_for :description do %>
  <p>Edit this template in <code>app/views/cards/show.html.erb</code>.</p>
  <% end %>

  <div class="container-fluid">
    <div class="row">
      <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
        <div class="sheet sheet-condensed">
          <div class="sheet-inner p30">
            <div class="form-horizontal">
                            <div class="form-actions col-md-offset-2">
                <%= link_to fa_icon_tag("pencil") + ' Edit', edit_card_path(@card), class: 'btn btn-primary' %>
                <%= link_to 'Back', cards_path, class: 'btn' %>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>